# This is a basic workflow to help you get started with Actions

name: publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'Sources/**'
      - 'Package.swift'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Build docs
        run: >
          xcodebuild docbuild -scheme YumemiWeather \
              -derivedDataPath .build \
              -destination 'generic/platform=iOS'
          $(xcrun --find docc) process-archive \
              transform-for-static-hosting .build/Build/Products/Debug-iphoneos/YumemiWeather.doccarchive \
              --hosting-base-path ios-training \
              --output-path docs
      - uses: actions/upload-pages-artifact@v2
        with:
          path: docs
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v2
        id: deployment
